<link rel="stylesheet" href="../../../../default.css">
<script src="../../../../highlight.pack.js"></script> 
<script>hljs.initHighlightingOnLoad();</script>
<html><h3></h3><h3>Before Change</h3><pre><code class='java'>
    def test_custom_performance_check_failure(self):
        self.checkfile = &quotunittests/resources/frontend_checks.py&quot
        self.options = [ &quot--tag CustomPerformanceFailureCheck&quot ]
        <a id="change">command = os_ext.run_command(self._invocation_cmd())</a>
        self.assertIn(&quotFAILED&quot, command.stdout)

        &#47&#47 This is a normal failure, it should not raise any exception
        self.assertNotIn(&quotTraceback&quot, command.stderr)
        self.assertNotEqual(command.returncode, 0)

        <a id="change">partitions = re.findall(&quot&gt;&gt;&gt;&gt; Running regression on partition: (\S+)&quot,
                                command.stdout)</a>
        self.assertTrue(self._stage_exists(&quotCustomPerformanceFailureCheck&quot,
                                           partitions, self.prgenv))
        self.assertNotIn(&quotCheck log file:&quot, command.stdout)
</code></pre><h3>After Change</h3><pre><code class='java'>
        self.checkfile = &quotunittests/resources/frontend_checks.py&quot
        self.options = [ &quot--tag CustomPerformanceFailureCheck&quot ]

        <a id="change">returncode, stdout, stderr = self._run_reframe()</a>
        self.assertIn(&quotFAILED&quot, stdout)

        &#47&#47 This is a normal failure, it should not raise any exception
        self.assertNotIn(&quotTraceback&quot, stderr)</code></pre>